require_relative '../models/translation'
require_relative '../models/menu_item'
require_relative '../db' # Підключення DB = Sequel.connect(...)

# --- Переклади ---

LANGUAGES = {
  'uk' => {
    name: '🇺🇦 Українська',
    welcome: 'Вітаємо! Оберіть мову:',
    menu_title: '📋 Наше меню:',
    cart_title: '🛒 Ваш кошик:',
    cart_empty: 'Кошик порожній',
    add_to_cart: 'Додано до кошика!',
    remove_from_cart: 'Видалено з кошика!',
    order_button: '🛒 Кошик',
    back_button: '⬅️ Назад',
    clear_cart: '🗑 Очистити кошик',
    make_order: '📝 Оформити замовлення',
    enter_phone: 'Введіть ваш номер телефону:',
    enter_address: '📍 Введіть вашу адресу доставки:',
    order_summary: "📋 Підтвердження замовлення:\n\n",
    total: 'Загальна сума: ',
    phone: 'Телефон: ',
    address: 'Адреса: ',
    confirm_order: '✅ Підтвердити замовлення',
    order_sent: 'Замовлення відправлено! Очікуйте на дзвінок.',
    new_order: 'Нове замовлення',
    share_phone: '📱 Поділитися номером',
    error_occurred: 'Виникла помилка. Спробуйте ще раз або зверніться до підтримки.',
    delivery: 'Вартість доставки',
    share_phone_tip: "Будь ласка, натисніть кнопку або введіть номер вручну:",
    language_changed: '✅ Мову змінено',
    switching_page: 'Перемикаю сторінку…',
    unknown_action: 'Невідома дія',
    new_order_from: '🚚 Нове замовлення від',
    order_placed: '✅ Замовлення оформлено! Очікуйте підтвердження.',
    choose_filter: '🔐 Оберіть фільтр:',
    no_access: '🚫 У вас немає доступу до адмін-розділу.',
    unknown_command: "🤔 Не впевнений, що ви маєте на увазі. Ось що можна зробити:\n/start - обрати мову\n/menu - Переглянути меню\n/cart - Переглянути кошик\n/orders - Переглянути історію замовлень\n/help - інструкція.",
    phone_label: '📞 Телефон:',
    address_label: '🏠 Адреса:',
    order_label: '🧾 Замовлення:',
    total_label: '💵 Разом:',
    no_orders_yet: 'У вас ще немає замовлень.',
    status: '📦 Статус:',
    repeat: '🔁 Повторити',
    details: '📜 Деталі',
    previous: '⬅️ Попередні',
    next: '➡️ Наступні',
    page: 'Сторінка',
    status_pending: 'Очікує підтвердження',
    status_confirmed: 'Підтверджено',
    status_shipped: 'Відправлено',
    status_unknown: 'Невідомо',
    status_canceled: 'Скасовано',
    order_not_found: 'Немає такого замовлення.',
    order_details: '📋 Деталі замовлення #',
    no_orders_with_status: 'Немає замовлень зі статусом',
    confirm: '✅ Підтвердити',
    cancel: '❌ Відхилити',
    mark_shipped: '📦 Відправлено',
    order_confirmed_admin: '✅ Замовлення #%{id} підтверджено.',
    order_confirmed_user: 'Ваше замовлення #%{id} було підтверджене!',
    confirm_error: '⚠️ Неможливо підтвердити. Можливо, статус вже змінено.',
    order_cancelled_admin: '❌ Замовлення #%{id} відхилено.',
    order_cancelled_user: 'Ваше замовлення #%{id} було скасовано!',
    cancel_error: '⚠️ Не вдалося відхилити. Можливо, статус вже змінено.',
    order_shipped_admin: '📦 Замовлення #%{id} відправлено.',
    order_shipped_user: 'Ваше замовлення #%{id} було відправлено!',
    ship_error: '⚠️ Неможливо змінити статус. Можливо, замовлення не підтверджене.',
    instruction: "Інструкція:\n\n1. Натисніть /start та оберіть мову.\n2. Перейдіть у /menu та оберіть товари.\n3. Обрані товари потрапляють у кошик.\n4. У кошику перевірте замовлення, при потребі видаліть або змініть.\n5. Натисніть «Оформити замовлення».\n6. Введіть свій номер телефону — на нього зателефонують.\n7. Введіть точну адресу доставки.\n8. Очікуйте підтвердження.\n9. Перевірити статус можна у /orders.\n10. Повторити замовлення можна також у /orders — воно одразу потрапить у кошик."
  },
  'pl' => {
    name: '🇵🇱 Polski',
    welcome: 'Witamy! Wybierz język:',
    menu_title: '📋 Nasze menu:',
    cart_title: '🛒 Twój koszyk:',
    cart_empty: 'Koszyk jest pusty',
    add_to_cart: 'Dodano do koszyka!',
    remove_from_cart: 'Usunięto z koszyka!',
    order_button: '🛒 Koszyk',
    back_button: '⬅️ Wstecz',
    clear_cart: '🗑 Wyczyść koszyk',
    make_order: '📝 Złóż zamówienie',
    enter_phone: 'Wprowadź numer telefonu:',
    enter_address: '📍 Wprowadź adres dostawy:',
    order_summary: "📋 Potwierdzenie zamówienia:\n\n",
    total: 'Suma całkowita: ',
    phone: 'Telefon: ',
    address: 'Adres: ',
    confirm_order: '✅ Potwierdź zamówienie',
    order_sent: 'Zamówienie wysłane! Oczekuj na telefon.',
    new_order: 'Nowe zamówienie',
    share_phone: '📱 Udostępnij numer',
    error_occurred: 'Wystąpił błąd. Spróbuj ponownie lub skontaktuj się z pomocą.',
    delivery: 'Koszt dostawy',
    share_phone_tip: 'Proszę kliknąć przycisk lub wpisać numer ręcznie:',
    language_changed: '✅ Język został zmieniony',
    switching_page: 'Przełączam stronę…',
    unknown_action: 'Nieznana akcja',
    new_order_from: '🚚 Nowe zamówienie od',
    order_placed: '✅ Zamówienie złożone! Oczekuj potwierdzenia.',
    choose_filter: '🔐 Wybierz filtr:',
    no_access: '🚫 Nie masz dostępu do panelu administracyjnego.',
    unknown_command: "🤔 Nie jestem pewien, co masz na myśli. Możesz użyć:\n/start - wybierz język\n/menu - Zobacz menu\n/cart - Zobacz koszyk\n/orders - Historia zamówień\n/help - instrukcja.",
    phone_label: '📞 Telefon:',
    address_label: '🏠 Adres:',
    order_label: '🧾 Zamówienie:',
    total_label: '💵 Razem:',
    no_orders_yet: 'Nie masz jeszcze zamówień.',
    status: '📦 Status:',
    repeat: '🔁 Powtórz',
    details: '📜 Szczegóły',
    previous: '⬅️ Poprzednie',
    next: '➡️ Następne',
    page: 'Strona',
    status_pending: 'Oczekuje na potwierdzenie',
    status_confirmed: 'Potwierdzone',
    status_shipped: 'Wysłane',
    status_unknown: 'Nieznany',
    status_canceled: 'Скасовано',
    order_not_found: 'Nie znaleziono zamówienia.',
    order_details: '📋 Szczegóły zamówienia #',
    no_orders_with_status: 'Brak zamówień ze statusem',
    confirm: '✅ Potwierdź',
    cancel: '❌ Odrzuć',
    mark_shipped: '📦 Wysłano',
    order_confirmed_admin: '✅ Zamówienie #%{id} potwierdzone.',
    order_confirmed_user: 'Twoje zamówienie #%{id} zostało potwierdzone!',
    confirm_error: '⚠️ Nie można potwierdzić. Status mógł się już zmienić.',
    order_cancelled_admin: '❌ Zamówienie #%{id} odrzucone.',
    order_cancelled_user: 'Twoje zamówienie #%{id} zostało anulowane!',
    cancel_error: '⚠️ Nie udało się odrzucić. Status mógł się już zmienić.',
    order_shipped_admin: '📦 Zamówienie #%{id} wysłane.',
    order_shipped_user: 'Twoje zamówienie #%{id} zostało wysłane!',
    ship_error: '⚠️ Nie można zmienić statusu. Zamówienie może nie być potwierdzone.',
    instruction: "Instrukcja:\n\n1. Wpisz /start i wybierz język.\n2. Przejdź do /menu i wybierz produkty.\n3. Wybrane produkty trafiają do koszyka.\n4. Sprawdź zamówienie w koszyku, usuń lub zmień w razie potrzeby.\n5. Kliknij „Złóż zamówienie”.\n6. Podaj swój numer telefonu — zadzwonimy do Ciebie.\n7. Podaj dokładny adres dostawy.\n8. Poczekaj na potwierdzenie.\n9. Status zamówienia sprawdzisz w /orders.\n10. Możesz powtórzyć poprzednie zamówienie również w /orders — trafi od razu do koszyka."

  },
  'en' => {
    name: '🇬🇧 English',
    welcome: 'Welcome! Choose language:',
    menu_title: '📋 Our menu:',
    cart_title: '🛒 Your cart:',
    cart_empty: 'Cart is empty',
    add_to_cart: 'Added to cart!',
    remove_from_cart: 'Removed from cart!',
    order_button: '🛒 Cart',
    back_button: '⬅️ Back',
    clear_cart: '🗑 Clear cart',
    make_order: '📝 Place order',
    enter_phone: 'Enter your phone number:',
    enter_address: '📍 Enter your delivery address:',
    order_summary: "📋 Order confirmation:\n\n",
    total: 'Total amount: ',
    phone: 'Phone: ',
    address: 'Address: ',
    confirm_order: '✅ Confirm order',
    order_sent: 'Order sent! Expect a call.',
    new_order: 'New order',
    share_phone: '📱 Share phone',
    error_occurred: 'An error occurred. Please try again or contact support.',
    delivery: 'Delivery cost',
    share_phone_tip: "Please click the button or enter the number manually:",
    language_changed: '✅ Language changed',
    switching_page: 'Switching page…',
    unknown_action: 'Unknown action',
    new_order_from: '🚚 New order from',
    order_placed: '✅ Order placed! Await confirmation.',
    choose_filter: '🔐 Choose filter:',
    no_access: '🚫 You have no access to admin panel.',
    unknown_command: "🤔 Not sure what you mean. Here's what you can do:\n/start - choose language\n/menu - View menu\n/cart - View cart\n/orders - Order history\n/help - instructions.",
    phone_label: '📞 Phone:',
    address_label: '🏠 Address:',
    order_label: '🧾 Order:',
    total_label: '💵 Total:',
    no_orders_yet: 'You have no orders yet.',
    status: '📦 Status:',
    repeat: '🔁 Repeat',
    details: '📜 Details',
    previous: '⬅️ Previous',
    next: '➡️ Next',
    page: 'Page',
    status_pending: 'Pending',
    status_confirmed: 'Confirmed',
    status_shipped: 'Shipped',
    status_canceled: 'Скасовано',
    status_unknown: 'Unknown',
    order_not_found: 'No such order found.',
    order_details: '📋 Order details #',
    no_orders_with_status: 'No orders with status',
    confirm: '✅ Confirm',
    cancel: '❌ Cancel',
    mark_shipped: '📦 Shipped',
    order_confirmed_admin: '✅ Order #%{id} confirmed.',
    order_confirmed_user: 'Your order #%{id} has been confirmed!',
    confirm_error: '⚠️ Cannot confirm. Status may have changed.',
    order_cancelled_admin: '❌ Order #%{id} cancelled.',
    order_cancelled_user: 'Your order #%{id} has been cancelled!',
    cancel_error: '⚠️ Cannot cancel. Status may have changed.',
    order_shipped_admin: '📦 Order #%{id} shipped.',
    order_shipped_user: 'Your order #%{id} has been shipped!',
    ship_error: '⚠️ Cannot update status. Order may not be confirmed.',
    instruction: "Instructions:\n\n1. Press /start and choose your language.\n2. Go to /menu and select items.\n3. Selected items go into the cart.\n4. In the cart, check and adjust your order if needed.\n5. Click \"Place Order\".\n6. Enter your phone number — you’ll get a confirmation call.\n7. Enter the correct delivery address.\n8. Wait for order confirmation.\n9. You can check status via /orders.\n10. You can repeat previous orders from /orders — they'll go straight to the cart."

  },
  'ru' => {
    name: '🇷🇺 Русский',
    welcome: 'Добро пожаловать! Выберите язык:',
    menu_title: '📋 Наше меню:',
    cart_title: '🛒 Ваша корзина:',
    cart_empty: 'Корзина пуста',
    add_to_cart: 'Добавлено в корзину!',
    remove_from_cart: 'Удалено из корзины!',
    order_button: '🛒 Корзина',
    back_button: '⬅️ Назад',
    clear_cart: '🗑 Очистить корзину',
    make_order: '📝 Оформить заказ',
    enter_phone: 'Введите номер телефона:',
    enter_address: '📍 Введите адрес доставки:',
    order_summary: "📋 Подтверждение заказа:\n\n",
    total: 'Общая сумма: ',
    phone: 'Телефон: ',
    address: 'Адрес: ',
    confirm_order: '✅ Подтвердить заказ',
    order_sent: 'Заказ отправлен! Ожидайте звонка.',
    new_order: 'Новый заказ',
    share_phone: '📱 Поделиться номером',
    error_occurred: 'Произошла ошибка. Попробуйте еще раз или обратитесь в поддержку.',
    delivery: 'Стоимость доставки',
    share_phone_tip: 'Пожалуйста, нажмите или введите номер вручную:',
    language_changed: '✅ Язык изменён',
    switching_page: 'Переключаю страницу…',
    unknown_action: 'Неизвестное действие',
    new_order_from: '🚚 Новый заказ от',
    order_placed: '✅ Заказ оформлен! Ожидайте подтверждения.',
    choose_filter: '🔐 Выберите фильтр:',
    no_access: '🚫 У вас нет доступа к админ-панели.',
    unknown_command: "🤔 Не уверен, что вы имеете в виду. Вот, что можно сделать:\n/start - выбрать язык\n/menu - Просмотр меню\n/cart - Просмотр корзины\n/orders - История заказов\n/help - инструкция.",
    phone_label: '📞 Телефон:',
    address_label: '🏠 Адрес:',
    order_label: '🧾 Заказ:',
    total_label: '💵 Итого:',
    no_orders_yet: 'У вас пока нет заказов.',
    status: '📦 Статус:',
    repeat: '🔁 Повторить',
    details: '📜 Детали',
    previous: '⬅️ Предыдущие',
    next: '➡️ Следующие',
    page: 'Страница',
    status_pending: 'Ожидает подтверждения',
    status_confirmed: 'Подтверждено',
    status_shipped: 'Отправлено',
    status_unknown: 'Неизвестно',
    status_canceled: 'Скасовано',
    order_not_found: 'Такой заказ не найден.',
    order_details: '📋 Детали заказа #',
    no_orders_with_status: 'Нет заказов со статусом',
    confirm: '✅ Подтвердить',
    cancel: '❌ Отклонить',
    mark_shipped: '📦 Отправить',
    order_confirmed_admin: '✅ Заказ #%{id} подтверждён.',
    order_confirmed_user: 'Ваш заказ #%{id} был подтверждён!',
    confirm_error: '⚠️ Невозможно подтвердить. Возможно, статус уже изменён.',
    order_cancelled_admin: '❌ Заказ #%{id} отклонён.',
    order_cancelled_user: 'Ваш заказ #%{id} был отменён!',
    cancel_error: '⚠️ Не удалось отклонить. Возможно, статус уже изменён.',
    order_shipped_admin: '📦 Заказ #%{id} отправлен.',
    order_shipped_user: 'Ваш заказ #%{id} был отправлен!',
    ship_error: '⚠️ Невозможно изменить статус. Заказ, возможно, не подтверждён.',
    instruction: "Инструкция:\n\n1. Нажмите /start и выберите язык.\n2. Перейдите в /menu и выберите товары.\n3. Выбранные товары попадают в корзину.\n4. В корзине проверьте заказ, при необходимости удалите или измените.\n5. Нажмите «Оформить заказ».\n6. Введите номер телефона — мы вам перезвоним.\n7. Укажите точный адрес доставки.\n8. Ожидайте подтверждения заказа.\n9. Статус можно проверить в /orders.\n10. Повторить заказ можно также через /orders — он сразу попадёт в корзину."

  },
  'by' => {
    name: '🇧🇾 Беларуская',
    welcome: 'Вітаем! Выберыце мову:',
    menu_title: '📋 Наша мэню:',
    cart_title: '🛒 Ваша кошык:',
    cart_empty: 'Кошык пусты',
    add_to_cart: 'Дададзена ў кошык!',
    remove_from_cart: 'Выдалена з кошыка!',
    order_button: '🛒 Кошык',
    back_button: '⬅️ Назад',
    clear_cart: '🗑 Ачысціць кошык',
    make_order: '📝 Аформіць замову',
    enter_phone: 'Увядзіце нумар тэлефона:',
    enter_address: '📍 Увядзіце адрас дастаўкі:',
    order_summary: "📋 Пацвярджэнне замовы:\n\n",
    total: 'Агульная сума: ',
    phone: 'Тэлефон: ',
    address: 'Адрас: ',
    confirm_order: '✅ Пацвердзіць замову',
    order_sent: 'Замова адпраўлена! Чакайце званка.',
    new_order: 'Новая замова',
    share_phone: '📱 Падзяліцца нумарам',
    error_occurred: 'Узнікла памылка. Паспрабуйце яшчэ раз або звярніцеся ў падтрымку.',
    delivery: 'Кошт дастаўкі',
    share_phone_tip: 'Калі ласка, націсніце кнопку або ўвядзіце нумар уручную:',
    language_changed: '✅ Мову зменена',
    switching_page: 'Пераключаю старонку…',
    unknown_action: 'Невядомая дзеянне',
    new_order_from: '🚚 Новы заказ ад',
    order_placed: '✅ Заказ аформлены! Чакайце пацверджання.',
    choose_filter: '🔐 Абярыце фільтр:',
    no_access: '🚫 У вас няма доступу да адміністрацыйнага раздзела.',
    unknown_command: "🤔 Не ўпэўнены, што вы маеце на ўвазе. Вось што можна зрабіць:\n/start - выбраць мову\n/menu - Глядзець меню\n/cart - Глядзець кошык\n/orders - Гісторыя заказаў\n/help - інструкцыя.",
    phone_label: '📞 Тэлефон:',
    address_label: '🏠 Адрас:',
    order_label: '🧾 Заказ:',
    total_label: '💵 Усяго:',
    no_orders_yet: 'Вы яшчэ не маеце заказаў.',
    status: '📦 Статус:',
    repeat: '🔁 Паўтарыць',
    details: '📜 Падрабязнасці',
    previous: '⬅️ Папярэднія',
    next: '➡️ Наступныя',
    page: 'Старонка',
    status_pending: 'Чакае пацверджання',
    status_confirmed: 'Пацверджана',
    status_shipped: 'Адпраўлена',
    status_canceled: 'Скасовано',
    status_unknown: 'Невядома',
    order_not_found: 'Такі заказ не знойдзены.',
    order_details: '📋 Падрабязнасці замовы #',
    no_orders_with_status: 'Няма заказаў са статусам',
    confirm: '✅ Пацвердзіць',
    cancel: '❌ Адхіліць',
    mark_shipped: '📦 Адправіць',
    order_confirmed_admin: '✅ Заказ #%{id} пацверджаны.',
    order_confirmed_user: 'Ваш заказ #%{id} быў пацверджаны!',
    confirm_error: '⚠️ Немагчыма пацвердзіць. Магчыма, статус ужо зменены.',
    order_cancelled_admin: '❌ Заказ #%{id} адхілены.',
    order_cancelled_user: 'Ваш заказ #%{id} быў скасаваны!',
    cancel_error: '⚠️ Не атрымалася адхіліць. Магчыма, статус ужо зменены.',
    order_shipped_admin: '📦 Заказ #%{id} адпраўлены.',
    order_shipped_user: 'Ваш заказ #%{id} быў адпраўлены!',
    ship_error: '⚠️ Немагчыма змяніць статус. Магчыма, заказ не пацверджаны.',
    instruction: "Інструкцыя:\n\n1. Націсніце /start і выберыце мову.\n2. Перайдзіце ў /menu і выберыце тавары.\n3. Выбраныя тавары трапляюць у кошык.\n4. Праверце замову ў кошыку, пры патрэбе выдаліце або змяніце.\n5. Націсніце «Аформіць замову».\n6. Увядзіце нумар тэлефона — мы патэлефануем.\n7. Увядзіце дакладны адрас дастаўкі.\n8. Чакайце пацверджання.\n9. Праверыць статус можна праз /orders.\n10. Паўтарыць замову таксама можна ў /orders — яна адразу трапіць у кошык."

  }
}


LANGUAGES.each do |locale, data|
  data.each do |key, value|
    DB[:translations].insert_conflict(target: [:locale, :key], update: { value: value }).insert(
      locale: locale,
      key: key.to_s,
      value: value
    )
  end
end


# --- Меню ---

MENU_ITEMS = [
  { id: 1, name_uk: 'Вареники з вишнею', name_pl: 'Pierogi z wiśniami', name_en: 'Dumplings with cherries', name_ru: 'Вареники с вишней', name_by: 'Варэнікі з вішняй', price: 38 },
  { id: 2, name_uk: 'Вареники з картоплею', name_pl: 'Kluski z ziemniakami', name_en: 'Dumplings with potatoes', name_ru: 'Вареники с картофелем', name_by: 'Варэнікі з бульбай', price: 38 },
  { id: 3, name_uk: 'Вареники з полуницею та м\'ятою', name_pl: 'Pierogi z truskawkami i miętą', name_en: 'Dumplings with strawberries and mint', name_ru: 'Вареники с клубникой и мятой', name_by: 'Варэнікі з трускаўкай і мятай', price: 38 },
  { id: 4, name_uk: 'Вареники з солодким творогом', name_pl: 'Pierogi z serem na słodko', name_en: 'Dumplings with sweet cottage cheese', name_ru: 'Вареники со сладким творогом', name_by: 'Варэнікі з салодкім тварагом', price: 38 },
  { id: 5, name_uk: 'Вареники з солоним творогом', name_pl: 'Pierogi z serem solonym', name_en: 'Dumplings with salted cottage cheese', name_ru: 'Вареники с соленым творогом', name_by: 'Варэнікі з салёным тварагом', price: 38 },
  { id: 6, name_uk: 'Вареники з телятиною та м\'ятою', name_pl: 'Pierogi z cielęciną i miętą', name_en: 'Dumplings with veal and mint', name_ru: 'Вареники с телятиной и мятой', name_by: 'Варэнікі з цяляцінай і мятай', price: 38 },
  { id: 7, name_uk: 'Пельмені зі свининою', name_pl: 'Pielmieni z wieprzowiną', name_en: 'Pork dumplings', name_ru: 'Пельмени со свининой', name_by: 'Пельмені са свініны', price: 38 }
]


MENU_ITEMS.each do |item|
    DB[:menu_items].insert_conflict(target: :id, update: {
    name_uk: item[:name_uk],
    name_pl: item[:name_pl],
    name_en: item[:name_en],
    name_ru: item[:name_ru],
    name_by: item[:name_by],
    price: item[:price],
    updated_at: Time.now
  }).insert(
    id: item[:id],
    name_uk: item[:name_uk],
    name_pl: item[:name_pl],
    name_en: item[:name_en],
    name_ru: item[:name_ru],
    name_by: item[:name_by],
    price: item[:price],
    created_at: Time.now,
    updated_at: Time.now
  )
end

puts "SEED DONE !"